### ISSUE TITLE
Can not get out of screensaver mode

### ISSUE THREAD

**Issue by greppp** [tiagovaz/eblab#16]
When the screensaver is On, we can't get out of the screensaver.

- When putting an rfid badge on top of it, we hear the relay clicking that means it reads and process. 

- When pressing the side button for one second nothing happens.

- when pressing the button for 3 second it reboots and is back to normal.

I don't know if it is related to #12 as i didn't describe clearly that issue.

**Comment by tiagovaz** [comment]
Done. Added a 'xscreensaver -deactivate' call each time a rfid card is read.

**Comment by greppp** [comment]
Problem still present

**Comment by tiagovaz** [comment]
removed screensaver. too much annoyance. will see if screen will burn, maybe not.
