### ISSUE TITLE
Screensaver start while cutting (and the machine stops)

### ISSUE THREAD

**Issue by greppp** [tiagovaz/eblab#17]
J'etais en train de graver le cadeau d'anniversaire de marion et le screensaver s'est enclenché, du coup ca m'a log out. Une chance la machine s'est mise en pause, j'ai débranché le Pi et rebranché, je me suis reloggé et j'ai appuyé sur Enter sur le laser et la job a repris là où elle était.

**Comment by tiagovaz** [comment]
no screensaver meh.
